site_name: BCMS Manual â€“ Alpha
site_url: https://manual-alpha.bcms.ai

theme:
  name: material

nav:
  - Home: index.md
  - Main: Main.md
  - Live Feed: "Live Feed.md"
  - Login & User: "Login & User.md"
  - Dashboard: Dashboard.md
  - The Top Bar: "The Top Bar.md"

  - Administration:
      - Overview: Administration/Administration.md
      - Core Management: "Administration/Core Management.md"
      - System: Administration/System.md

  - Bird Deterrent System:
      - Overview: "Bird Deterrent Sys/BirdDeterrentSys.md"
      - System Status: "Bird Deterrent Sys/System Status.md"

  - Event Management:
      - Overview: "Event Management/Event Management.md"
      - Detection: "Event Management/Detection.md"
      - Impact: "Event Management/Impact.md"
      - Inspection: "Event Management/Inspection.md"

  - Statistics:
      - Overview: Statistics/Statistics.md
      - Detection: Statistics/Detection.md
      - Impact: Statistics/Impact.md
      - System: Statistics/System.md

  - Utilities:
      - Overview: Utilities/Utilities.md
      - Notifications: Utilities/Notifications.md

  - Info:
      - Overview: Info/Info.md
      - About: Info/About.md
      - Support: Info/Support.md