site_name: BCMS® Ventur – System Manual
site_url: https://manual-alpha.bcms.ai
language: it

theme:
  name: material

  # Logo and favicon (place these files under docs/images/)
  logo: images/bcms-logo-ventur.svg       # or .png
  favicon: images/bcms-favicon.png

  palette:
    - scheme: default
      primary: white          # we’ll override colors via CSS vars
      accent: orange

extra_css:
  - stylesheets/extra.css

nav:
  - 0. Index: index.md
  - 1. The Top Bar: "shared/The Top Bar.md"
  - 2. Live Feed: "shared/Live Feed.md"
  - 3. Dashboard: shared/Dashboard.md
  - 4. Bird Deterrents: "shared/Bird Deterrent Sys/BirdDeterrentSys.md"
  - 5. Eventi:
      - Panoramica: "shared/Event Management/Event Management.md"
      - Detection: "shared/Event Management/Detection.md"
      - Impact: "shared/Event Management/Impact.md"
      - Inspection: "shared/Event Management/Inspection.md"
  - 6. Utilities:
      - Panoramica: "shared/Utilities/Utilities.md"
      - Notifications: "shared/Utilities/Notifications.md"
  - 7. Statistics:
      - Panoramica: "shared/Statistics/Statistics.md"
      - Detection: "shared/Statistics/Detection.md"
      - Impact: "shared/Statistics/Impact.md"
      - System: "shared/Statistics/System.md"
  - 8. Registers: "shared/Registers.md"
  - 9. Admin: "shared/Administration/Administration.md"
  - 10. Glossario: "shared/Glossario.md"
  